services:
  _defaults:
    autowire: true
    autoconfigure: true

  designerei\ContaoPageTeaserBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,DependencyInjection}

  designerei\ContaoPageTeaserBundle\Controller\ContentElement\PageTeaserController:
    public: true
    arguments: ['@contao.image.studio']